import { build } from "esbuild";

await build({
  entryPoints: ["worker/src/index.js"],
  outfile: "worker/wloc-worker.js",
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  legalComments: "none",
  banner: { js: "/* wloc-worker.js - generated by npm run build:worker */" },
});
