import { build } from "esbuild";

function buildBundle(entry, output, name) {
  return build({
    entryPoints: [entry],
    outfile: output,
    bundle: true,
    format: "iife",
    platform: "neutral",
    target: "es2020",
    minify: true,
    legalComments: "none",
    banner: { js: `/* ${name} - generated by npm run build:wloc */` },
  });
}

await Promise.all([
  buildBundle("src/wloc/runtime.js", "dist/wloc.js", "wloc.js"),
  buildBundle("src/wloc/settings.js", "dist/wloc-settings.js", "wloc-settings.js"),
]);
